name: Android CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t android-test-image

    - name: Run Docker container
      run: |
        docker run -d --name android-test-container -p 4723:4723 android-test-image

    - name: Wait for Appium
      run: |
        echo "Waiting for Appium..."
        until $(curl --output /dev/null --silent --head --fail http://localhost:4723/wd/hub/status); do
          printf '.'
          sleep 5
        done

    - name: Install Appium drivers
      run: docker exec android-test-container appium driver install uiautomator2

    - name: Run tests
      run: docker exec android-test-container pytest /app/appiumtests/test_webapp.py
